### ISSUE TITLE
DDEV_HOST_WEBSERVER_PORT Variable missing in a commands/host/ command

### ISSUE THREAD

**Issue by tkieslich** [ddev/ddev#1812]
**Describe the bug**
If i use the env command in a custom Command in commands/host/ i see the DDEV_HOST_DB_PORT like 32768 but not the DDEV_HOST_WEBSERVER_PORT which should be 32770. In my case.

**To Reproduce**
create a command commands/host/env.sh with:

```
#!/usr/bin/env bash
env
```

run ddev env.sh
compare the Ports with the Output of
`docker ps`

**Expected behavior**
have the right Portt in DDEV_HOST_WEBSERVER_PORT env Variable.

**Version and configuration information (please complete the following information):**
 - MacOs 10.14
 - Docker version 19.03.1
 - ddev version v1.10.2 
 - config.yaml 
```
APIVersion: v1.10.2
name: ****
type: php
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
- ***-de
- ***-at
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
omit_containers: [dba]
use_dns_when_possible: true
timezone: Europe/Berlin
```

**Additional context**
in need the Port for a command like this:
```
socat tcp-listen:8899,reuseaddr,fork tcp:localhost:32770
#socat tcp-listen:8899,reuseaddr,fork tcp:localhost:${DDEV_HOST_WEBSERVER_PORT}
```

without to set the Port manualy. With this command it is possible to access the Host with IP:8899 for testing with other devices.

**Comment by rfay** [comment]
It's important to get this to work. It's a little more work than I thought when first looking at the issue, but it's definitely a key thing. (Also DDEV_HOST_HTTPS_PORT)

**Comment by rfay** [comment]
Apparently the problem is that app.HostWebserverPort and app.HostHTTPSPort aren't set by default when they're not overridden by config, so they're empty in 

https://github.com/ddev/ddev/blob/bbb2caca961784aa68d0511848823464a009f14b/pkg/ddevapp/ddevapp.go#L1900-L1901 

We need to figure out what they are when they're not explicitly overridden in config. For DDEV_HOST_DB_PORT, this is done in 

https://github.com/ddev/ddev/blob/bbb2caca961784aa68d0511848823464a009f14b/pkg/ddevapp/ddevapp.go#L1869-L1876

Once we figure out what the (default-assigned) port is in this case where app.HostWebserverPort is empty, we can use the technique like DDEV_HOST_DB_PORT does.
