### ISSUE TITLE
Bundle ngrok with the Windows installer

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#1925]
The ngrok.exe can be easy integrated to the Windows installer too and would make life of devs a little bit easier.

I already asked for the permission to do so, if we don't get an (positive) answer we can simply integrate it as a automatic download similar to Docker Desktop.

**Comment by gilbertsoft** [comment]
I have not received answer from ngrok. How will we proceed? I suggest to inculde the binary to the installer as own component.

**Comment by rfay** [comment]
Let's keep waiting a bit. I pinged them also just now on their "contact us" form on their web page. 

It's quite possible that the ngrok in Chocolatey (2.0) is unmaintained, as their current is 2.3.35, so that would argue even more for bundling it. 

Interestingly... https://chocolatey.org/packages/ngrok : It shows in the license link a link to ngrok v1's Apache license, clearly inappropriate.  Shows software source as https://chocolatey.org/packages/ngrok, not true. 

This is kind of too bad.

**Comment by rfay** [comment]
Let's go ahead and bundle. And probably remove from the chocolatey recipe, since that one isn't kept up-to-date. If they ever get back to us and object, we'll happily remove it. They must be living life large on a beach or something.

**Comment by rfay** [comment]
Finally got a response!


> From: Alan Shreve <support@ngrok.com> 
> hi randy -
> sorry about the delayed response. yep, you bet, please bundle away
> - alan
> Founder, ngrok.com

Link: https://mail.google.com/mail/u/2/#inbox/FMfcgxwGCQbMZZnvcqrBpXfzgswVxgjz

**Comment by rfay** [comment]
ngrok approved us bundling; And we include ngrok as a dependency in chocolatey.

**Comment by rfay** [comment]
I don't think we need to do this since people generally install with chocolatey.
