### ISSUE TITLE
Symlinks are not resolved in project root when creating a new project

### ISSUE THREAD

**Issue by benk-cogapp** [ddev/ddev#2385]
**Describe the bug**

When creating a new ddev project in a path that contains symlinks, I would expect that symlinks would be resolved to the real path to the directory, so that the project will work however I access. In practice the symlinked path is used as the project root as-is, which then results in issues trying to use ddev from the real path.

**To Reproduce**
1. `mkdir foo`
2. `ln -s foo bar`
3. `cd bar && ddev config`
4. `ddev start`
5. `cd ../foo`
6. `ddev stop`

**Expected behavior**

ddev stop would stop the project.

**Actual behaviour**

![image](https://user-images.githubusercontent.com/12101645/87686524-7caff580-c77c-11ea-87be-22a5cd789fb3.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 19.04
 - Docker version information
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information: 1.15.0
 - config.yaml contents for the misbehaving project
```
name: bar
type: php
docroot: ""
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Comment by rfay** [comment]
I think the problem here is that you *changed* the location of your project. It already existed, then you changed the symlinking arrangement. All you have to do is `ddev stop --unlist bar` and then `ddev start`

**Comment by benkyriakou** [comment]
From my point of view I didn't change the location of any of the files - I just changed how I accessed the directory. The project is still in exactly the same place in the filesystem, and the symlink existed before I created the project.

In a more real-world example, I saw this because I have `~/Documents/workspace` symlinked to `/w` on my machine for ease of access. Depending on how I `cd` to a project directory, ddev can refuse to run despite me having neither moved any files or changed any configuration. I'd argue that this is incorrect behaviour, and I've never had any issues with any other software, virtualisation or otherwise, because of this arrangement.

**Comment by rfay** [comment]
It's really complex trying to keep people from shooting themselves in the foot at the same time as trying to allow things like what you're doing. It does sound like there may be a realpath() call missing.

**Comment by benkyriakou** [comment]
Totally, and I can see this would have some backwards compatibility considerations if someone is used to accessing their project via a symlink since the project path would then change from under then if the path was `realpath`ed, but to my mind both paths are equally valid ways of accessing the project and it seems wrong that that's enough to cause my ddev environment to stop working without being reconfigured.

**Comment by rfay** [comment]
This seems like a complex case, and nobody else has ever chimed in in 3 years, so I think we should close it. I just tried it out and this confused mutagen as well.
