### ISSUE TITLE
Move back to official mkcert packages and update mkcert

### ISSUE THREAD

**Issue by dennisameling** [ddev/ddev#2583]
https://github.com/FiloSottile/mkcert/pull/284 has been merged, so mkcert is also officially available for arm64 now. That means we don't need the fork `drud/mkcert` anymore. This issue is just as a notification that we should switch back at some point; I don't have the bandwidth to do so at the moment, but when I do, I'll report here before I start working on it.

If anyone has time to work on this that'd be great 🚀

**Comment by rfay** [comment]
Thanks. I agree that we don't have to move fast on this. In fact... we don't know how good the new official release is yet. It got a lot of sudden commits.

**Comment by rfay** [comment]
DDEV will be available for Apple Silicon before too terribly long; mostly as soon as Docker Desktop has a tech preview. 

Since the maintainer of mkcert is leading the charge for golang support on Apple Silicon, I imagine he'll add a package there, but if he doesn't, we'll want to stay on our fork (and put a darwin/arm64 build on it).

**Comment by rfay** [comment]
mkcert is built for apple silicon in homebrew, but the repo doesn't build releases for it. I opened https://github.com/FiloSottile/mkcert/issues/329 requesting the build for Apple Silicon.

**Comment by rfay** [comment]
This is blocked by https://github.com/FiloSottile/mkcert/pull/359 for Apple Silicon.

**Comment by rfay** [comment]
Note that mkcert is available via `apt-get` in Ubuntu 22.04, and also that DDEV includes mkcert in the ddev apt package.

**Comment by rfay** [comment]
I'm pretty sure that this issue is obsolete. The two usages I see are 

https://github.com/ddev/ddev/blob/e0c89d6e952ebb90872d8390e2cca2faa5bd27e2/containers/ddev-webserver/Dockerfile#L92

and https://github.com/ddev/ddev/blob/e0c89d6e952ebb90872d8390e2cca2faa5bd27e2/containers/ddev-webserver/Dockerfile#L216

I guess it's done for the normal build and the prod build separately?

Anyway, I'm pretty sure the ddev/mkcert is obsolete already. 

Closing, and I'll archive ddev/mkcert
