### ISSUE TITLE
`ddev add-on get` should allow specifying optional settings

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Some `ddev add-on get` add-ons can use minor configuration overrides. For example, the version of a redis image might want to be overridden. 

### Describe your solution

Use a flag, `--environment`? 

### Describe alternatives

People currently have to manually edit `docker-compose.*.yaml` and then remove the #ddev-generated from a file that is part of an add-on.

**Comment by rfay** [comment]
@gilzow This was 
* https://github.com/drud/ddev-platformsh/issues/28
It doesn't appear there's a way to do this, because the project ID is not available in this file at this time.

**Comment by rfay** [comment]
`ddev pull` takes environment variables on the command line. That might work here.

**Comment by rfay** [comment]
Some ideas:

* a .ddev/.env file is already supported for docker-compose.*.yaml, it would probably work fine already.
* docker-compose.*-extra.yaml already works.
* config.*-extra.yaml already works.; 
* .env file could perhaps be applied to `config.*.yaml` as well

**Comment by seebeen** [comment]
An extended flag to `ddev get` command would work. Something like this

```bash
$ ddev get ddev/ddev-redis --version $RELEASE_VERSION
```

It would be bound to the repo version, not the actual docker image in the plugin (if the plugin has one)

**Comment by rfay** [comment]
Thanks for the thinking @seebeen - but since `ddev get` has no idea whatever what things might want to be replaced/configured, how is that going to work out? 

And what happens the next time they update the add-on and forget the argument?

**Comment by stasadev** [comment]
I opened a draft PR:

- #6406

---

> Use a flag, `--environment`?

I added this flag to `ddev get`. It takes into account the `.env.*` files inside the `.ddev' folder.

> a `.ddev/.env` file is already supported for `docker-compose.*.yaml`, it would probably work fine already.

I chose not to write to `.ddev/.env` because it may contain sensitive information and people usually don't want to commit that file.

Instead, I used a file name according to the add-on, such as `.ddev/.env.<addon-name>`, e.g. `.ddev/.env.redis`.

All `.env.*` files that end in `.example` will be ignored.

> And what happens the next time they update the add-on and forget the argument?

This `.ddev/.env.redis` is automatically expanded when running `docker-compose config`, this allows you to run `ddev get` without arguments that are already saved and taken into account.

All environment variables in add-ons (which can be overridden) should have default values, for example `${REDIS_VERSION:-6-bullseye}`, not `${REDIS_VERSION}` - this will allow the add-on to work with older DDEV versions, and `.ddev/.env.redis` is completely optional when env has a default value.

**Comment by GuySartorelli** [comment]
> I chose not to write to `.ddev/.env` because it may contain sensitive information and people usually don't want to commit that file.
>
> Instead, I used a file name according to the add-on, such as `.ddev/.env.<addon-name>`, e.g. `.ddev/.env.redis`.

The point of `.env` files is that they're for that specific environment - I probably wouldn't want to commit `.env.<addon-name>` files any more than I'd want to commit `.env`, but that might just be me.

**Comment by stasadev** [comment]
Thanks for the input @GuySartorelli.

> I probably wouldn't want to commit `.env.<addon-name>` files any more than I'd want to commit `.env`

`.env.*` is much easier for users to understand and use instead of using the yaml file syntax, and it is natural for `docker-compose config` to accept it with the `--env-file` flag.

As an alternative, I can only see doing similar to `web_environment`, like `db_environment` or `redis_environment`, or converting everything to:

```yaml
environment:
  - service: web
    variables:
      - ENV1=foo
      - ENV2=bar
  - service: db
    variables:
      - ENV1=foo
      - ENV2=bar
  - service: redis
    variables:
      - ENV1=foo
      - ENV2=bar
```

But users can already define the `environment` in their respective `docker-compose.*.yaml` files, so I think this will only add more confusion, and `.env.*` seems like a good solution for me.

The other way is to read the individual `docker-compose.*.yaml` files and parse them, but this is an unknown area because after everything is merged into one file, the structure may change, and it's similar to the chicken-and-egg problem where I need to read something before adding env variables to it, but it may already be overridden in another `*override.yaml` file. I thought about it a lot and gave it up for now.

If only we had a `docker-compose` SDK for Go, it would be much easier.
