### ISSUE TITLE
Don't manage Craft 3 .env, Fix `*_SITE_URL`

### ISSUE THREAD

**Issue by bossanova808** [ddev/ddev#4650]
The recently added settings management for Craft projects broke my ddev / **Craft 4** project - when I came back to it after some time away - and in a way I couldn't immediately understand from this error:

```
Failed to start craft-dev: template: templateStringToFile:/home/jeremy/ddev-projects/c4-dev/.env:7: function "siteUrl" not defined
```

Prior to this the project was working fine for a few months, it was only on coming back to it that the new settings management kicked in, with a ddev upgrade.  

Thus, I think `disable_settings_management ` should definitely default to `false` for _existing_ projects. 

As per the other issue discussion, I think `PRIMARY_SITE_URL` should be added only if the existing & typical `CRAFT_SITE_URL` is not already present - otherwise it's just doubling up right?

The config setting is the default way to define this in Craft:
https://craftcms.com/knowledge-base/how-craft-determines-the-site-url
https://craftcms.com/docs/2.x/config-settings.html#siteurl

And thus, with Craft 4's new approach to .env variables, `CRAFT_SITE_URL` is the de facto default way of actually implementing this.

Personally I am not super fussed about Mailhog, other than to note that Craft has a config setting for a similar thing already:
https://docs.craftcms.com/v3/config/config-settings.html#testtoemailaddress

```
        'testToEmailAddress' => (\craft\helpers\App::env('SEND_ALL_EMAILS_TO')) ?? null,
```

So in Craft's case, Mailhog is likely to be irrelevant to most and I would expect that to be set as a matter of course in `.env` files for dev environments.

_Originally posted by @bossanova808 in https://github.com/drud/ddev/issues/4552#issuecomment-1429132626_
            
(Adding as a new issue per request)

**Comment by rfay** [comment]
I can certainly understand why you would want `disable_settings_management` to default given your experience, but thousands of people have been using it with automatic settings management for years, and there are advantages to it as well, people like it quite a lot that they can spin up a project with no knowledge of settings. The full docs on settings are at https://ddev.readthedocs.io/en/latest/users/usage/cms-settings/, explaining all of the possibilities.

As far as the current usage (aimed at Craft 4), here is the current logic and the environment variables that are changed if settings management is disabled. If you can be specific about what you think is inappropriate, it can be fixed; a PR would be welcome, but please be specific about what you think is not correct and please link to the authority for your opinion.

https://github.com/drud/ddev/blob/8fe332777d896c662b0404b2a8fbf8973161c8d7/pkg/ddevapp/craftcms.go#L113-L139

**Comment by bossanova808** [comment]
Well, for Craft 3 those values might be the _usual_ ones, but they were allowed to be anything (and I have personally seen many variants) - so not sure those assumptions are safe for Craft 3 at all, I'd suspect more than a few sites would break with that approach.

But realistically, most folks will be using ddev with Craft 4, so perhaps not that important.

For Craft 4 - 'PRIMARY_SITE_URL' is not right, I think.  As per the others, 'CRAFT_SITE_URL' would be the standard there, as per the link:
https://craftcms.com/docs/2.x/config-settings.html#siteurl

Other than that, the rest seem fine - but in all cases, ddev would skip those, if they are already present in the `.env`, right?  

If so, and if the correct `CRAFT_SITE_URL` was looked for/used instead, then my dev environment would not have broken (which is my primary goal when using ddev - that it be a stable and repeatable dev environment!) - and these changes would have been a non-issue... 

(Apart from perhaps being surprised to see MAILHOG in there - and note, there was no comment or whatever to tell me that ddev had inserted these, and I fairly strong think there should be).

@lindseydiloreto Can I drag you in here, is the above reasonable?  Obviously I'm not your typical Craft dev as such, so I don't want to misinform anyone!

**Comment by lindseydiloreto** [comment]
@bossanova808 Well, I should start by apologizing to @rfay... I've already bludgeoned this dead horse, I'm sure he's sick of hearing me talk about it. 🙂

I don't see using `disable_settings_management` as a good long-term solution. It feels more like a band-aid for projects which really need it, not something that Craft should regularly require.

> For Craft 4 - `PRIMARY_SITE_URL` is not right, I think. As per the others, `CRAFT_SITE_URL` would be the standard there, as per the link: https://craftcms.com/docs/2.x/config-settings.html#siteurl

^ This is correct. On Craft 4, the standard is `CRAFT_SITE_URL`.

Here's the central piece of information that this whole conversation should be revolving around... the magical `CRAFT_` prefix **did not exist before Craft 4.0**. Prior to that, it was the "wild west" of environment variables, where all important settings were being manually pumped through a PHP config file (either `db.php` or `config.php`).

I agree with @rfay that Craft 3 projects should be generally excluded from consideration. It's easy enough to use the `php` project type on a Craft 3 site and have zero issues (forgoing a couple of minor niceties in `craftcms`). Or if the user must use the `craftcms` project type, perhaps DDEV could detect it and ignore their `.env` file entirely.

And the good news is, DDEV is already performing a check against existing env variables to determine which version of Craft is being used. However, it should probably be looking for **`CRAFT_DB_SERVER`** in order to determine whether the site is running Craft 4 or higher.

Here's my proposed change for the snippet shown earlier. I can't program in Go, so apologies if this is a little off...

```go
 // If the site is at least Craft 4
 if _, ok := envMap["CRAFT_DB_SERVER"]; ok { 
 	envMap = map[string]string{
 		"CRAFT_DB_DRIVER":       driver, 
 		"CRAFT_DB_SERVER":       "db", 
 		"CRAFT_DB_PORT":         port, 
 		"CRAFT_DB_DATABASE":     "db", 
 		"CRAFT_DB_USER":         "db", 
 		"CRAFT_DB_PASSWORD":     "db", 
 		"MAILHOG_SMTP_HOSTNAME": "127.0.0.1", 
 		"MAILHOG_SMTP_PORT":     "1025", 
 		"CRAFT_SITE_URL":        app.GetPrimaryURL(), 
 	}
 } 

// If older than Craft 4, don't change anything!
```

This would...
- Use the correct `CRAFT_SITE_URL` variable
- Only impact Craft 4+ sites
- Bypass changes in Craft 3 sites

I wish I knew Go, I'd submit a PR for this stuff. But it may be too dangerous for me to be tinkering around in there directly. Could be talked into submitting a PR with some hand-holding, though! 😬

**Comment by rfay** [comment]
It seems like we're making some progress now. Let's see if we can get the proper set of things together:

1. Detect Craft 3 and don't manage settings for it.
2. Change PRIMARY_SITE_URL to CRAFT_SITE_URL

Can you suggest how to detect Craft 3 vs 4?

Does *_SITE_URL even need to be set? Is it useful? Few CMSs insist on knowing their explicit URL, and the ones that do (like Wordpress and Magento) are worse off for it :)

**Comment by rfay** [comment]
None of these explain why @bossanova808 had trouble though. We'll need you to study that further please...

**Comment by bossanova808** [comment]
Those conclusions sound right to me.  

I don't really know anything about how ddev actually works (I'm barely able to keep up with Craft, really....I run a totally unrelated full time business, i.e. I'm one of those crazy owner-operators types that insisted on building most of our website myself...).  I've just simply not dug in to it to date.

But there's a `composer.json` in the main folder of every Craft project and e.g. for this project mine starts with:

```
{
  "require": {
    "craftcms/cms": "^4.0.0",
```    

And for the Craft 3 version I have:

```
{
  "require": {
    "craftcms/cms": "^3.7.1",
````

Would that not work?  I believe every Craft project will have one of those.

I personally have always set the site URL.  I don't know if it is optional.

In terms of what happened - I don't really know any more than the error I've listed above.  Which comes from ddev right?  It didn't make sense to me and honestly I didn't really know where to start with it, so I popped into the ddev discord and heard about disabling the settings stuff from `tyler36` - which got me going (well, I need to deal with some DB stuff, but that is not related).

More than happy to dig further if you'd like to run me through what to do, to do so?

(BTW - thanks so much for the help etc.  All of this is in the spirit of making Craft <> ddev good buddies :) )

**Comment by rfay** [comment]
Thanks all - I think this should help.

This message:

`Failed to start craft-dev: template: templateStringToFile:/home/jeremy/ddev-projects/c4-dev/.env:7: function "siteUrl" not defined`

is in fact a message from DDEV... saying that it can't parse the .env file, because it had invalid contents.  But it had invalid contents before DDEV tried to add things to it. I don't know what was there before, but it was apparently something that some other apps would ignore, but DDEV's env-reader choked on it. I imagine it was invalid env syntax. 

I do think it would be reasonable not to choke in this case, and skip adding anything to the env file. Adding that to the to-do-list above.

**Comment by bossanova808** [comment]
Hmm, fairly confident my .env file is fine (I certainly have no issues either with the old Craft 3 version or the Craft 4 I am moving to).  But I'm not really up on the formal .env requirements so I suppose if the parser is fussier than Craft's, that is possible.  My gut feeling, though, is that all I have are simple constants in there - URLs, a few API key things, etc. - very standard for Craft at least - so if mine fails, pretty sure a lot would!

Thanks again!

**Comment by rfay** [comment]
Thanks @bossanova808 - if you still have the .env file that did this, would you be willing to share it? If there's anything sensitive in it you could edit it.

**Comment by timkelty** [comment]
> For Craft 4 - PRIMARY_SITE_URL is not right, I think. As per the others, CRAFT_SITE_URL would be the standard there

This isn't quite right. There is in fact, no "standard" for this variable, because in Craft 4 there is no `siteUrl` config setting (because multi-site). Setting this env wouldn't magically do anything unless you manually referenced it in your site's URL. In that regard, naming it `CRAFT_*` is actually a bit misleading.

> In fact... according to https://github.com/craftcms/cms/pull/11912, the CRAFT_WEB_URL and CRAFT_WEB_ROOT were created for this explicit purpose. Perhaps we should be using those instead?

@lindseydiloreto this is exactly what I would suggest. Since a DDEV install is always going to "single-site" by default, setting these in env allows you to just set your primary site's URL to `@web` and you're all set.

**Comment by lindseydiloreto** [comment]
Ok great, thanks for weighing in! So it sounds like we should ditch any mention of `PRIMARY_SITE_URL` or `CRAFT_SITE_URL`, and run with this instead...

```
CRAFT_WEB_URL="https://projectname.ddev.site"
CRAFT_WEB_ROOT="/var/www/html/web"
```

For Craft 4, of course. None of these would be applied to a Craft 3 site.

Is that what you're endorsing @timkelty?

**Comment by rfay** [comment]
It sounds to me like just removing the `*_URL` in this case is the best situation? The security issue doesn't seem that relevant in this context?

**Comment by lindseydiloreto** [comment]
Sorry for the late response! You (accidentally) raise a good philosophical question @rfay...

### Should these two environment variables even be set in a local environment?

I lean towards "yes", for the following reasons:
 - **Convenience.** These values can (and frequently do) feed into other values that get parsed out via PHP. There are several common Craft methods (like [`url`](https://craftcms.com/docs/4.x/dev/functions.html#url)) which attempt to use these values if they exist.
 - **General security practices.** Since it's important for these values to exist in _every other environment_, it may be good practice for people to be accustomed to seeing them as part of the `.env` file. It's pretty common to copy an `.env` file between environments, then simply change the relevant values.

As usual, I'll defer to Tim (or another authority) if I'm mistaken about any of this!

**Comment by lindseydiloreto** [comment]
I'm not a `composer` expert, but I saw @khalwat mention this on Discord...

```sh
composer show craftcms/cms
```

Would that help us determine the current version of Craft?

Looks like this command returns a JSON of the package data from the `composer.lock` file...

```sh
ddev composer show craftcms/cms --locked --format=json
```

**Comment by acalvino4** [comment]
I noticed that when I start ddev, it adds several lines to my `.env`:

```sh
CRAFT_DB_USER=db
CRAFT_DB_PASSWORD=db
MAILHOG_SMTP_HOSTNAME=127.0.0.1
MAILHOG_SMTP_PORT=1025
CRAFT_DB_DRIVER=pgsql
CRAFT_DB_PORT=5432
CRAFT_DB_SERVER=db
CRAFT_DB_DATABASE=db
```

is this related to this issue?

The problem for me is that I generally prefer setting these explicitly via my config rather than relying on the `CRAFT_` magic variables. So my setup is working without those added lines, but all the same ddev is cluttering my file with them.

**Comment by rfay** [comment]
For Craft 3, you're better off just using the `php` project type, and it won't try to do that. 

You can also use `disable_settings_management: true` and DDEV won't attempt to do this.

See https://ddev.readthedocs.io/en/latest/users/usage/cms-settings/ for more detail.

**Comment by rfay** [comment]
You wouldn't miss out on anything... You just manage settings yourself, which is what it sounds like you want to do,😂
