### ISSUE TITLE
MySQL 5.7 configured in ddev is using 100% RAM

### ISSUE THREAD

**Issue by cgarciaba** [ddev/ddev#4862]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

I expected to run the project without issues. 

### Actual Behavior

When a project configured to run with MySQL 5.7, starts, in the part that the script is creating the dba container, the process mysqld uses 100% RAM avaliable and make the system unresponsive and freezes.

### Steps To Reproduce

1. In Fedora 38, with the lastest version of Docker and DDEV
2. In a Drupal 9 project, with MySQL 5.7 configured
3. Run 'ddev start'
4. See and suffer the error.

### Anything else?

I changed the Mysql versión to 8.0 and the error does not occur.

**Comment by rfay** [comment]
Could you please do the requested `ddev debug test` and put it in a gist on gist.github.com (or another pastebin, or attach a file)? That lets us know many more details other than "latest version fo docker and ddev". 

It sounds like the problem may have to do with the behavior of your database. 

Does this happen when you do a basic installation of a CMS or framework (for example, one of the [quickstarts](https://ddev.readthedocs.io/en/latest/users/quickstart/) or does it only happen with your particular project and a specific database loaded?

**Comment by stasadev** [comment]
This is not directly related to DDEV.

I had the same problem on Arch. This is due to the changed limits in Docker 23 (and underlying Golang).

For context read this bug report https://bugs.archlinux.org/task/77481, it describes everything (this is already fixed in Arch).

Regarding Fedora 38 - I don't know when this will be fixed in your distro.

In the meantime, you can override the limits https://bbs.archlinux.org/viewtopic.php?pid=2084430.

**Comment by rfay** [comment]
This seems to be explained, thanks @stasadev , closing for now, happy to continue the conversation here or elsewhere, and happy to reopen this. Like you say, this doesn't seem to be related to DDEV.
