### ISSUE TITLE
Add example file for web commands

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I just started using the wonderful [Custom Commands](https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/) feature to trigger a series of Drush commands, as well as run Unix commands. It works really well, and it's easy to write the command files.

It would have been great if there had been an example `web` Custom Commands  file, both to hit the ground running, as well as show case what's possible.

### Describe your solution

Add an example file with some example commands, and the available variables.

**Comment by tyler36** [comment]
If you are looking for more inspiration, check the global web commands `$HOME/.ddev/commands/web`

**Comment by gitressa** [comment]
Thanks @tyler36!

**Comment by tyler36** [comment]
@gitressa  Happy to help.

Oh, and just incase you haven't seen it, checkout https://github.com/ddev/ddev-contrib , it contains a lot of DDEV-related things that are useful but not required in DDEV core.

**Comment by rfay** [comment]
Since there are so many examples of
* [host commands](https://github.com/ddev/ddev/tree/master/pkg/ddevapp/global_dotddev_assets/commands/host)
* [web commands](https://github.com/ddev/ddev/tree/master/pkg/ddevapp/global_dotddev_assets/commands/web)
* [db commands](https://github.com/ddev/ddev/tree/master/pkg/ddevapp/global_dotddev_assets/commands/db)

I'm going to close this for now, but happy to continue the conversation here or elsewhere. Perhaps we need more links to those in the docs? Your PR will be welcome if you see a good place for it, thanks.

**Comment by gitressa** [comment]
I added the command in [Working efficiently with the command line > Report with custom DDEV command](https://www.drupal.org/docs/develop/development-tools/working-efficiently-with-the-command-line#s-report-with-custom-ddev-command), so the `ddev report` example has now found a home :)
