### ISSUE TITLE
Improve usability of of django4 and python projects

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5171]
### The problem

DDEV introduced Python/Django support in v1.22.0.

The good things:
* DDEV has direct support for [Django4](https://ddev.readthedocs.io/en/latest/users/quickstart/#django-4-experimental) (but not yet Django5) and also for more generic [Python/Flask](https://ddev.readthedocs.io/en/latest/users/quickstart/#pythonflask-experimental) projects. More discussion in [Experimental Configurations](https://ddev.readthedocs.io/en/latest/users/configuration/experimental/#django4-and-python-project-types)
* It has decent automated tests, including a Django4 configuration, a simple Flask configuration. Each of these passes our automated testing, and problems are immediately noticed.

The bad things:
* These features do not yet have a community. As far as I know, less than five people have experimented with these capabilities. DDEV is fundamentally dependent on its community, which is key to its success with PHP projects. Users notice what they need, and they let us know. DDEV would have long drifted away except for its community involvement, and we do not have anything like that for Python/Django.
* We chose Gunicorn for the webserver, and Gunicorn, unlike php-fpm, absolutely refuses to run if the supported app's settings are not correct, and setting those requires some expertise and the ability to read logs to sort it out. Every user that I'm familiar with has stumbled at this point. DDEV tries to prompt about the basic issues, and the docs mention this, but users just stumble here.

Platform.sh has stated its clear plans for DDEV to support Python projects, but we are definitely not there yet, and I'd love to have more feedback about how we could be more successful, especially getting people started at the beginning. I'm willing to use something other than gunicorn if that can solve the problems. But the community problem will require far more significant efforts.

### Possible solutions

* Write better tutorials with specific examples
* Do screencasts
* Improve visibility of what's going on with gunicorn, or use another webserver

**Comment by chellman** [comment]
Hey @rfay sorry for the radio silence, was traveling.  I appreciate the changes that made it into 1.22, and I'll try to help however I can with Django improvements.

It seems like PyCharm is improving support for remote interpreters; the jankiness of working on a container-based project has made me slow to push on this before ddev support was available.  So if JetBrains can get support for everything working well, I'll be trying to switch to using DDEV on my main Django project at work.

My work project is the first one I've ever worked on for a meaningful length of time, which means I'm not overly familiar with gunicorn, but I am familiar with bashing on a project until I can get it running. 🤣 

With all that being said, I will try to understand how this stack works better so I can make recommendations.  I've been able to get my Django project up and running via `ddev ssh` and running `python manage.py runserver`.  I'm not yet sure why gunicorn isn't happy.

**Comment by jeroenpeters1986** [comment]
hi! I tried this django4 support recently and I hope it's okay to share my experience here. 

After my first failed attempt a while ago I cleaned everything and did it again. At first I only read https://ddev.readthedocs.io/en/latest/users/configuration/experimental/#django4-and-python-project-types 
In my second attempt I also found https://ddev.readthedocs.io/en/latest/users/quickstart/#django-4-experimental
This time it went better. After a few config changes (I have a non-typical setup because I use MariaDB instead of Postgres) it worked without all the CSS/JS and so on. For a typical server-deployment I am generating those files and serve them seperatly but for development I have always liked to use Django's `runserver`. So my aim was to be running runserver instead of gunicorn, as this does require me to setup extra webserver stuff.

As I didn't get to see where I could change the gunicorn setup (I have admit I didn't look at all the code) I changed my `nginx-site.conf` file file as follows:
 * I removed `#ddev-generated`
 * I changed the (port of the) proxy_pass line to `proxy_pass http://localhost:8001;`

After this, I tried different hooks with `post-start`. Unfortunately using `nohup python manage.py runserver 0.0.0.0:8001 &` didn't work. I don't really know why as I could not debug this very well.
Using `python manage.py runserver 0.0.0.0:8001` ofcourse works, but it will never actually "complete"  the startup of DDEV (okay, it's the last command to run, but nevertheless it feels akward).

So for now, I have done something to my config.yml which is also awkward, but has a few advantages (like I can login to the session and restart runserver when I need). 
```config.yaml
webimage_extra_packages: [python3-dev, default-libmysqlclient-dev, libmariadb-dev, build-essential, screen]
hooks:
  post-start:
    - exec: "screen -dmS runserver bash -c 'python manage.py runserver 0.0.0.0:8001; exec bash'"
```

Now I know this is probably no good as any kind of solution for everyone or to include in DDEV, but the nature of this issue is to explore the improvement of usability. I hope this give a little bit of an insight in how I work with it. Don't get me wrong, I am very happy that I can now also use DDEV with my Django project!

**Comment by rfay** [comment]
Thanks so much for your report!

**Comment by rfay** [comment]
Right now I'm on a bicycle tour in Patagonian Chile, but would very much like to revisit your experiences and maybe we can work together on this in the coming months.

**Comment by jeroenpeters1986** [comment]
Wow that sounds cool! Have fun and if you have the time you can mention me here or get in contact with me like via my site. I hopefully have even more experience then. Have a good time!Op 16 dec 2023 om 16:47 heeft Randy Fay ***@***.***> het volgende geschreven:﻿
Right now I'm on a bicycle tour in Patagonian Chile, but would very much like to revisit your experiences and maybe we can work together on this in the coming months.

**Comment by jeroenpeters1986** [comment]
@rfay Since a bit, Django 5 is out. I know DDEV now explicitly supports django4. Will Django5 be supported? I have seen that for this Python shoudl be upgraded. I tried such, but to no avail. I do not want to loosely compile a python somewhere on the container and then use that. I saw that a new debian base would provide a newer Python version (which Django5 supports), but I could not get it to work. 
It's not problem and no hurry for me, just out of curiousity I was wondering if the base of the web-container will be upgraded? If so, Django5 would also be supported automatically.

**Comment by rfay** [comment]
I would imagine that it's not hard to support django5, maybe it works already. Upgrading python3 is super easy.

Are you currently using DDEV with django4? 

The key problem we have with python/django is community feedback at this point. We'd love to make it better, but it's all crickets out there. So glad to have you speaking up!

**Comment by jeroenpeters1986** [comment]
hi @rfay when I typed my previous comment I didn't have all the numbers. The web container is currently shipped with Python3.9, while Django5 requires 3.10 or more.
At this moment `webimage_extra_packages: [python3.10]` does not work, because it isn't available in the (apt) repo.

I know some things about Debian myself so I thought how hard can it be, add an apt-get repo with a backport and be done with it. But that doesnt seem to work because of other dependencies. There was one package, but that doesn't come with pip as they say "you can just use the python3.9 one". This is true for packages that do not require 3.10 or higher...
That was on this page: https://community.home-assistant.io/t/home-assistant-core-python-3-10-backport-for-debian-11-bullseye/528439

I did try to make a Dockerfile for the webcontainer with this
```
RUN wget -qO- https://pascalroeleven.nl/deb-pascalroeleven.gpg | sudo tee /etc/apt/trusted.gpg.d/deb-pascalroeleven.gpg && \
    echo "deb http://deb.pascalroeleven.nl/python3.10 bullseye-backports main" > /etc/apt/sources.list.d/python310.list

RUN apt-get -qq update
RUN apt-get -qq install --no-install-recommends --no-install-suggests -y python3.10
```
But it wasn't enough to work

That page also mentioned that Debian Bookworms contains Python3.10 (or higher). So then I though, let's just use a different base for the webcontainer. I tried several things but I did not succeed on this. It was a month or so ago but I think I didn't figure out where I could change/find the initial "FROM" directive for the most downward layer of the web container. 

I hope this gives you a bit of an insight in what I tried. If you had some ideas of your own on this (and you have the time to share them here), I am open to try those.

**Comment by rfay** [comment]
Thanks, this is probably worth spinning off into another issue, as it's really about how to get Python 3.10 onto a Debian 11 machine. It does look like the options are slim! However, I imagine `pyenv` would work fine. 

However, this .ddev/web-build/Dockerfile.python310 does work fine:

```
RUN wget -qO- https://pascalroeleven.nl/deb-pascalroeleven.gpg | sudo tee /etc/apt/trusted.gpg.d/deb-pascalroeleven.gpg
RUN echo "deb http://deb.pascalroeleven.nl/python3.10 bullseye-backports main" >/etc/apt/sources.list.d/python310.list
RUN apt update && apt install -y python3.10
```

After `ddev restart` I get 
```
$ ddev exec python3.10 --version
Python 3.10.13
```

If you need python3.10 to be the default `python` (which can break things) you have to do `update-alternatives` etc. 

Debian Bookworm 12, which should be the base of ddev-webserver in DDEV v1.23 this Spring, has python 3.11 by default. (https://github.com/ddev/ddev/pull/5579)

**Comment by rfay** [comment]
@jeroenpeters1986 what I'm really interested in is whether you've been using DDEV successfully for any python-related projects, how it went, what needs to be improved.

**Comment by jeroenpeters1986** [comment]
@rfay hi Randy, my first experience was also commented here in december (https://github.com/ddev/ddev/issues/5171#issuecomment-1858839350). I use DDEV for PHP a lot, so I thought i'd give it a try for python and now it's working I am happy with it. I am using the runserver quite a lot so I still have those modifications in place, so I can also see the output. This is something I think more people would need probably
I am currently succesfully running https://github.com/jeroenpeters1986/pyBudgie with it.

**Comment by rfay** [comment]
Thanks so much, so glad to hear that you're using this in the wild!

**Comment by jeroenpeters1986** [comment]
Really thank you @rfay I love the simplicity that DDEV offers, and now I can use the same way of working with DDEV. I will try  your suggestion for the Python 3.10. Also waiting for 1.23 works for me for a definitive solution as this is hobby project I work on on the side. I will keep you updated and if there any things you want to know from me, please dont hesitate to ask

**Comment by jeroenpeters1986** [comment]
I got python3.10 installed, but I don't really know what I am supposed to do next. I bet pyenv would work and getting pip3.10 there, but I don't really see where I should put it.
I know there is a .venv there, but I don't know where I would have to hook in to get that updated with my Pyhton3.10. Also, if I would have know, I feel like it's a bit wonky, as I would override all the defaults here that make Python possible.

**Comment by rfay** [comment]
Agreed about pyenv. It does seem like fighting a major battle with Debian 11. I'm surprised they forced a python version that wasn't supported by such a major version of Debian.

**Comment by jeroenpeters1986** [comment]
Yes I agree with you. Especially since Buster is LTS. Django has gone really fast the last year or two in releases, but also in these requirements. But for now it's no biggie for me, as my project works just fine on Django4 :-)

**Comment by rfay** [comment]
@jeroenpeters1986 DDEV HEAD now has python 3.11.2, would love to have you give it a try. We'll be doing prereleases for v1.23.0 before too long, but right now you can test using the instructions at https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits-on-head

I don't think you'll run any risks by doing that, and would love to hear your results.

**Comment by rfay** [comment]
Updated the OP, https://github.com/ddev/ddev/issues/5171

**Comment by jeroenpeters1986** [comment]
Hi Randy, thanks for the effort! I am currently sick in bed so I hope I can give you some results at the end of the week. Thanks so much!Op 18 feb 2024 om 18:30 heeft Randy Fay ***@***.***> het volgende geschreven:﻿
Updated the OP, #5171

**Comment by jeroenpeters1986** [comment]
Hi @rfay , sorry for the late reply but this virus have kept me under the weather for at least two weeks. I tried it yesterday and it works great!
Since I am using MySQL in my Django Project I am having this line in my config.yaml (also I use `screen`):
```
webimage_extra_packages: [python3-dev, pkg-config, default-libmysqlclient-dev, libmariadb-dev, build-essential, screen]
```
The `pkg-config` is new for me since this release. It seems like it wasn't installed on bookworm, but that's okay. The error message that pip threw was clear enough for me to know that it needed pkg-config.
The database-dev packages make it possible to `pip install mysqlclient==2.2.0` for me.
Also, Django 5.0 is working fine!

**Comment by rfay** [comment]
Thanks so much for testing this! And I'm glad to hear you're feeling better now, wishing you a full and quick recovery.

**Comment by rfay** [comment]
Thanks so much for giving this a go @jeroenpeters1986 - We just had so little uptake that it doesn't make sense to continue the feature.

**Comment by chellman** [comment]
Sorry I couldn't help more with this.  It would have been nice to see it, but I understand pulling it if no one's using it.

**Comment by jeroenpeters1986** [comment]
Hi @rfay I meant to reply yesterday, but it's a bit of a hectic time at work haha. Anyway, totally understandable! Luckily PyCharm and the works are facilitating me as well in my little Python/Django projects. So despite it's a pity this will be dropped, it's not too big of a loss. And it's probably best for your own focus on the product :-)

Were you using it yourself btw?

I am using DDEV a huge lot at my work at IMPRES, so still.. thanks so much for DDEV :-)

**Comment by jeroenpeters1986** [comment]
Yes, you are right, not much of a python community here, so it's a good decision to drop it in this case. Keep up the good work for DDEV and when I see something that I can, I' ll try to contribute (with this or my other jeroenpeters1986 account haha)
