### ISSUE TITLE
messages: ticker_interval: -1 does not disable tickers

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

The new messages feature says that you can disable the ticker completely with:
```
messages:
    ticker_interval: -1
```  

But that doesn't actually work. If you set that and then roll back the `last_ticker_at` value in ~/.ddev/.state.yaml, you will still get a ticker message.

### Actual Behavior

x

**Comment by gitressa** [comment]
Thanks for fixing this. I added the below lines in my _~/.ddev/global_config.yaml_ and it seems like the "Tip of the day" has stopped:

```
messages:
    ticker_interval: -1
```

I do still get this warning, how can I disable it?

```
 IMPORTANT MESSAGE                                                                                                                   
 If you have warnings about omit_containers: [dba] try `grep "^omit_containers.*dba" */.ddev/config.yaml` in the directory where you keep your projects
```

**Comment by rfay** [comment]
Also, I just turned off the daily message for now, 
* https://github.com/ddev/remote-config/pull/10

**Comment by gitressa** [comment]
Thanks as always @rfay for a fast response! It's much appreciated.

I do think "Tip of the day" could be useful, if it was less intrusive, I might not feel I need to turn it off. The main reason I do that for now, is because it was too large, and when I start DDEV, it looks like an important error message. A discrete one or two lines might work better?

**Comment by gitressa** [comment]
The last few weeks this error message is shown in big red when starting up DDEV:

> IMPORTANT WARNING
> If you're running Colima v0.5.6, don't `brew upgrade` to v0.6.* until you save your databases or you'll lose them. `ddev snapshot -a`. https://twitter.com/randyfay/status/1723701983549456541

As a user, I only need to see this warning once or twice. I think showing it continually defeats the purpose, since repeatedly showing warnings will make the user ignore them, since the warning may be:

1. Not relevant
1. Already seen

In my opinion, such warning should be shown at most maybe three times, and then expire, to never be shown again.

**Comment by rfay** [comment]
I had 
* https://github.com/ddev/remote-config/pull/21
ready to go so I just pulled it.

**Comment by gitressa** [comment]
Perfect, thanks!

How about my idea to only show warnings a set number of times? Very quickly such "LOOK AT ME!!!!"-blobs of content become annoying. If another warning shows up, the users will be less likely to heed the actual content -- they have become banner-blind be permanent exposure.

**Comment by rfay** [comment]
Have you considered how wonderful it is that we can communicate an important message without a new release? As always, contributions that do not increase complexity are welcome.

**Comment by gitressa** [comment]
It's a great feature, I agree :)

I created #5568, let's see if it's possible to tweak the set up, without getting too complex.
