### ISSUE TITLE
umask 0027 prevents healthcheck in ddev-router

### ISSUE THREAD

**Issue by ted933** [ddev/ddev#5239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

DDev should run with umaks 0027 set in user's ~/.bashrc

### Actual Behavior

In ddev-router the file /healthcheck.sh is not readable for others and the health check fails.

### Steps To Reproduce

1. On Ubuntu 22.04 set umask 0027 in user's ~/.bashrc
2. Install docker
3. Install ddev
4. Create dummy ddev project
5. Start project => error: ddev-router failed to become ready: health check timed out
6. Connect to the ddev-router instance e.g. 'docker exec -it --user root ddev-router bash' to check the file permissions of /healthcheck.sh

### Anything else?

Looks like [Failed to start ddev router #1237](https://github.com/ddev/ddev/issues/1237) but has different cause.
May be a similar issue as [web_extra_daemons start fails with error "ERROR (no such group)" #4872
](https://github.com/ddev/ddev/issues/4872)

**Comment by rfay** [comment]
Super interesting! 
* https://github.com/ddev/ddev/issues/1237 isn't related I don't think; that didn't have to do with build and was related to the legacy router. 
* But obviously https://github.com/ddev/ddev/issues/4872 is the same general class of problem. 

I guess DDEV can change file perms before build. In this exact case I'm thinking we should have a DDEV-built traefik image instead of using the upstream traefik image directly; that would also solve this particular case. 

Thanks for the careful work sorting this out, and also for doing the research in the issue queue.

**Comment by rfay** [comment]
Fix for this is in now, it will be in v1.22.2 in a couple of weeks.
 
I'd love it if you'd test, see https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits-on-head

But I'm pretty sure it should be completely resolved. thanks for reporting!
