### ISSUE TITLE
Output something when an image is being rebuilt

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Every now and then I get curious into ddev getting quite a bit to start, prompt me to troubleshoot and then I remember it's probably building the image again (maybe something changed, or the cache bust, or I upgraded docker/ddev).

### Describe your solution

I know you can get a lot more output with debug, but I wonder if a simple line saying this is happening could be useful.

Something like "your xxxx container is being built, it can take a few minutes" or something of the like.

**Comment by rfay** [comment]
I agree.

You can already see what's going on with `export DDEV_DEBUG=true`, but you have to know in advance to do that. 
I think it would be better to always say the build start and end (there's always a build, it just might be cached). 

It's easy to do... since we already do it for DDEV_DEBUG.

I've been confused by this many times.

**Comment by rfay** [comment]
A PR would be welcome. It's just in app.Start() before and after the docker-compose build.
