### ISSUE TITLE
`brew install --HEAD` should provide a canonical DDEV/git version, not `vHEAD-<hash>`

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5433]
In working with 
* #4630, 
* #5379 and 
* #5424

I installed HEAD with `brew unlink ddev && brew install ddev/ddev/ddev --HEAD --fetch-HEAD`. 

I get:
```
# ddev --version
ddev version vHEAD-0ceead6
```

This obviously will bypass any constraint as it's not a valid semver. This is not an important issue I think, just something I saw by chance, however, I wonder how hard would it be for the HEAD version to be something more similar to `v1.22.3-hash` or whatever pre-release scheme you can think best for HEAD. This would at least allow it to work with `ddev_version_constraint`.

**Comment by hanoii** [comment]
I don't think I can dive into this one unless you point to to where and it's not super difficult, but you probably have a lot more release information than me. I wonder where the last released version can be obtained when building HEAD on homebrew or the like. And I guess this would have to make it do for all platforms.

**Comment by hanoii** [comment]
Again, I should stress that using HEAD might actually be OK to be outside of any constraint, after all, it's HEAD :)

**Comment by rfay** [comment]
Unfortunately, brew builds in a context without any information about the real git version. If you get the HEAD version from the CI build (https://ddev.readthedocs.io/en/latest/developers/building-contributing/, https://nightly.link/ddev/ddev/workflows/master-build/master) it will be normal:

```
$ ./ddev --version
ddev version v1.22.3-33-g0ceead660
```

If you build HEAD yourself with a normal git checkout, it will also be like that. 

The problem is that brew builds with `make VERSION=vHEAD-0ceead6 COMMIT=vHEAD-0ceead6` for example, resulting in `$ ddev --version
ddev version vHEAD-0ceead6`


It's possible that we could figure out how to improve https://github.com/ddev/homebrew-ddev/blob/master/Formula/ddev.rb#L23

But... we'd have to figure out `#{version}` better, so figure out how to coach homebrew on a real respectable version.

**Comment by rfay** [comment]
My bet is we can convince homebrew to do something like `make VERSION=$(git describe --tags --always --dirty) COMMIT=${commit}`, but my ruby isn't strong enough to figure that out right away.
