### ISSUE TITLE
Add dark-mode supported sponsor logos on Github

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

Currently, some sponsor logos our Github homepage are barely readable or look strange.

### Expected Behavior

Highlight our wonderful sponsors.

![image](https://github.com/ddev/ddev/assets/7234392/ba4bb5f4-8eef-425f-921c-4d59fe463fdd)

(image from ddev.com)

### Actual Behavior

![image](https://github.com/ddev/ddev/assets/7234392/5be7570c-ef68-468c-b258-acb5367adc04)

### Steps To Reproduce

Visit: https://github.com/ddev/ddev#wonderful-sponsors

### Anything else?

There were recent updates to https://ddev.com/ that fixed the issue there. We should be able to re-use those images.

**Comment by tyler36** [comment]
@Firesphere pointed it out the issue on [Discord ](https://discord.com/channels/664580571770388500/1068592266752573440/1169456953248972842).

**Comment by rfay** [comment]
@bmartinez287 want to take a look?

**Comment by bmartinez287** [comment]
I will look into this. https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/
the picture element should work nicely here.

**Comment by bmartinez287** [comment]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github

**Comment by rpkoller** [comment]
+1 for opening the issue as well as the suggestion about the use of the picture element by @bmartinez287 . but the only detail i wonder about would it make sense to ask all the sponsors if they have variants of their logo for dark backgrounds (and in case they dont have if they are ok with the suggested inversion of colors done in the expected behavior screenshot). but some of the logos there couldnt be inverted and therefore fail WCAG SC 1.4.11 like agaric, the parenthesis of tag1, the heart of undpaul, the background square for centaros logo to name a few details.

**Comment by bmartinez287** [comment]
We could ask them after we replace them. Ib cases were their reply might just be "it looks fine". Some logos prove a unique challenge since they are a single icon. But in most cases altering the SVG text seems to make it ally compatible.

We could ask them now, but this might be low in their priorities list so they might say yes but give us no timeframe for it.

**Comment by rpkoller** [comment]
yes i agree but i am just worried that some of them might have strict rules in regards of their corporate identity and changing colors in logos might alter that corporate identity therefore i think give them a headsup early on might be a good idea in any way.

**Comment by rfay** [comment]
The real problem here is that I'm going to be unwilling to bother them :)

**Comment by bmartinez287** [comment]
https://github.com/ddev/ddev/commit/b3c1539d9e6331b6c5d7fa5a401bfc43ae65b2e4
I'm not sure where that PR hid those files. Searching for them does not bring them up in the repo.
Is ![DDEV featured sponsor logos] hidden behind some secure setting I need access too?

**Comment by rfay** [comment]
Those things come from ddev.com, 100% open source.

**Comment by bmartinez287** [comment]
I gues, I never seen the    ...... ![something] syntax on markup. What is that called?

**Comment by bmartinez287** [comment]
<img width="1042" alt="Screenshot 2023-11-08 at 1 11 50 PM" src="https://github.com/ddev/ddev/assets/39039024/00387454-9737-4f54-acdf-50d8d1684b9d">
