### ISSUE TITLE
Allow setting the default database type/version in global config

### ISSUE THREAD

**Issue by mbomb007** [ddev/ddev#5693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently, the default DB version is in the Go code.

```go
// MariaDBDefaultVersion is the default MariaDB version
const MariaDBDefaultVersion = MariaDB104
```

### Describe your solution

I would like to be able to specify the default, perhaps per project type, in the global config YAML. That way, whenever I create a new Drupal project, it will default to using the DB type and version that I am targeting.

### Describe alternatives

The current alternative is to edit config.yaml prior to running `ddev config`. However, if I forget, then I have to drop the database and rerun the commands to get it set up.

### Additional context

This isn't super important or high priority, but it's something that I would like to have.

**Comment by rfay** [comment]
You don't have to edit config.yaml prior to running `ddev config`. Just use `ddev config --project-type=<type> --database=mysql:8.0` or whatever. I do know the problem though, I also forget to set database type correctly. 

I don't think that setting a global database type default is probably something that would be a high priority right now though, since you're the first to ever suggest it. I do wish that all config items had global defaults though. 

Interested in doing a PR? There are a number of recent PRs that added global default config.

**Comment by tyler36** [comment]
My company prefers to use Postgres for most projects. We would benefit from a setting where new projects default to Postgres.

**Comment by rfay** [comment]
That's not *exactly* what would happen here, unless the global config were set up for each user in advance. But thanks for the vote!

**Comment by rfay** [comment]
This would be solved by 
* https://github.com/ddev/ddev/issues/5696

**Comment by rfay** [comment]
I don't expect to pursue this.
