### ISSUE TITLE
unable to ping pkg.ddev.com to download ddev 

### ISSUE THREAD

**Issue by trade74** [ddev/ddev#5709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

I am unable to access pkg.ddev.com to download DDEV

curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
curl: (6) Could not resolve host: pkg.ddev.com

also

ping pkg.ddev.com

Pinging pkg.ddev.com.furyns.com [2600:1f18:677:2305:b778:8a3c:28fe:1996] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

### Expected Behavior

to download ddev

### Actual Behavior

error accessing pkg.ddev.com

### Steps To Reproduce

accessing from Australian IP

### Anything else?

accessing from Australian IP

**Comment by tyler36** [comment]
`curl` is working for me

```
$ curl -fsSL https://pkg.ddev.com/apt/gpg.key
-----BEGIN PGP PUBLIC KEY BLOCK-----

xsFNBGLEq48BEADbBkfXTYk03cOhnKq ...
```

But `ping` is not ...

```
$ ping pkg.ddev.com

Pinging pkg.ddev.com.furyns.com [34.236.177.99] with 32 bytes of data:
Request timed out.
Request timed out.
...
```

Website appears up: https://pkg.ddev.com/

Accessing from Japan

**Comment by stasadev** [comment]
For me, just like for @tyler36.

@trade74 maybe it has something to do with IPv6 🤔:
```
curl: (6) Could not resolve host: pkg.ddev.com
```

**Comment by rfay** [comment]
Agreed, this is a problem with your internet setup, there's nothing we can do to help you. 

However, you have two completely different things happening. You show `Could not resolve host: pkg.ddev.com` first, which implies that your DNS resolution is broken. 

Then you show `ping pkg.ddev.com` successfully resolving. 

You shouldn't expect to be able to ping just any host on the internet, many are protected by firewalls, etc. 

However, this is what you should see:

```
 pkg.ddev.com
PING pkg.ddev.com.furyns.com (44.196.204.37): 56 data bytes
```

Closing because this is a problem on your end, but we're happy to continue the conversation.

Make sure you remove random things that might be in your hosts file, and check how your DNS is working. It shouldn't be returning an IPV6 address in the first place.
