### ISSUE TITLE
New config parameter: custom browser instead of `xdg-open ${FULLURL}`

### ISSUE THREAD

**Issue by nu111** [ddev/ddev#5953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I run `ddev launch` or `ddev phpmyadmin` the default browser opens up `xdg-open ${FULLURL}`. I'd like to be able to define a custom specific browser instead.

### Describe your solution

inside `.ddev/config.yaml` I would add a new optional line
```yaml
custom_browser: "~/Apps/firefox-dev/firefox"
```

**Comment by rfay** [comment]
I don't think this is easy to do because DDEV runs on many different platforms, and firefox exists in various places on each. 

`launch` is just a custom command that happens to be provided by DDEV though, so you can copy it or update it and remove #ddev-generated as you wish, https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/launch

You can also put it into your project if you want a particular behavior.

Since `launch` is just a helper tool to open a browser for you and is in no way important to the DDEV workflow, it doesn't make sense to add loads of options into it. 

Remember that you can open firefox at any time and navigate to your project on the URL bar. (That's all `ddev launch` does for you.)

More on custom/shell commands at https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/

**Comment by rfay** [comment]
I don't think we can do this generically as mentioned above, but contributions and ongoing thought are always welcome!
