### ISSUE TITLE
Expose TERM and COLORTERM (and maybe other) system env vars to ddev

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6174]
I am doing this on an add on: https://github.com/hanoii/ddev-pimp-my-shell/blob/1c5d2f5cd667edd7236c97844b172e769f0f67d3/config.pimp-my-shell.yaml#L25-L26, specially TERM was one that was bugging me as I use https://sw.kovidgoyal.net/kitty/faq/ that has needs its own termcap to function properly.

I wonder why this is not something happening by default, exposing useful and personal system environment variables to the running ddev if whether it should.

**Comment by rfay** [comment]
We go to a lot of effort to do COLUMNS and such. Last time I was in this territory there was too much friction between the shell in container and the shell on host to make it work, but contribution is welcome there.

**Comment by rfay** [comment]
A PR is welcome here, imitating what happens with LINES and COLUMNS as is done here, https://github.com/ddev/ddev/blob/165f36240c566b48a4e7f28448dfa0f08cfebd9e/pkg/ddevapp/app_compose_template.yaml#L213

It's just one line per item. I'm surprised TERM isn't there already.  Closing for now, looking forward to PR.

**Comment by rfay** [comment]
Full write-up with the actual colored terminal transcripts (replayed from the real captured escape sequences, not mockups) and the script used to draw the color bars: https://claude.ai/code/artifact/82e0889d-4251-448d-a00e-ef3afe12fac4

I ran the manual test plan from [PR #8669](https://github.com/ddev/ddev/pull/8669) against both `upstream/main` and the PR branch, using a real pty (`script(1)`) so `tput colors`/`$COLORTERM` reflect what an actual terminal session sees, not just piped output.

**Result:** on `upstream/main`, an interactive `ddev ssh` is stuck at `TERM=xterm` / `tput colors -> 8` / no `COLORTERM`, no matter what the host terminal supports. On the PR branch, the same session picks up the host's `TERM`/`COLORTERM`, `tput colors` resolves to `256`, an unresolvable host term (e.g. kitty's `xterm-kitty`) falls back to `xterm-256color` instead of forwarding broken, piped/non-interactive output is unchanged on both branches, and a `web_environment`-configured `TERM` still wins when there's no tty.

| Branch | Service / mode | host TERM | host COLORTERM | container TERM | tput colors |
|---|---|---|---|---|---|
| main | web, piped (no tty) | xterm-256color | truecolor | xterm | 8 |
| main | web, interactive | xterm-256color | truecolor | xterm | 8 |
| main | web, interactive | xterm-kitty | truecolor | xterm | 8 |
| main | db, interactive | xterm-256color | truecolor | xterm | 8 |
| PR | web, piped (no tty) | xterm-256color | truecolor | xterm | 8 |
| PR | web, interactive | xterm-256color | truecolor | xterm-256color | 256 |
| PR | web, interactive | xterm-kitty | truecolor | xterm-256color (normalized) | 256 |
| PR | db, interactive | xterm-256color | truecolor | xterm-256color | 256 |

**Comment by wazum** [comment]
@rfay the Claude Code artifact is nice 👍

**Comment by rfay** [comment]
Pretty fun :)
