### ISSUE TITLE
Allow DDEV nodejs_version to use external file as reference for node version

### ISSUE THREAD

**Issue by n8-dev** [ddev/ddev#6418]
### Is there an existing issue for this?

* https://github.com/ddev/ddev/issues/6071

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently I have a file that holds my node version used by various other parts of the project

Ultimately I'd like to not have to manage DDEV's config independantly of the other details that read this file.

### Describe your solution

Allowing `nodejs_version:` to accept `path/to/file` OR `version`

It would just take the version number from a defined file.
It can break if you pass something wrong, that's on you.

The filename is irrelevant.

### Describe alternatives

N/A

### Additional context

https://github.com/ddev/ddev/issues/6071

**Comment by rfay** [comment]
Please be specific about how DDEV would understand the format of the file you propose. 

Then explain how it would work for others with different file formats.

Could you please show the contents of the file you use?

**Comment by GuySartorelli** [comment]
> Please be specific about how DDEV would understand the format of the file you propose.
> ...
> Could you please show the contents of the file you use?

The file would simply contain the version number to use, in any format currently supported by the `nodejs_version` configuration option. For example

```text
20
```

or 

```text
20.0.0
```

Since the file contents are already in the format that ddev expects, once we have read the file contents we don't need to do any massaging or extra parsing of the value - we can just use it the same way that the current value of `nodejs_version` is used.

Note that there are several known tools that use a file with this format. A probably-non-exhaustive list of files with this format was provided in the original issue, but I'll list them here for convenience:

- [.node-version](https://github.com/shadowspawn/node-version-usage) (seems to be the most widely used - or at least used by the most tools)
- [.n-node-version](https://github.com/tj/n)
- [.nvmrc](https://github.com/nvm-sh/nvm)

> Then explain how it would work for others with different file formats

For files which contain anything other than a version in the formats that `nodejs_version` currently accepts, I would recommend an error be thrown.

> While you're at it, please explain how you use this file in other contexts, thanks.

Scenarios where files of this format are used include (but may not be limited to):

1. Collaborating with developers who are _not_ using ddev. These developers can use a tool which uses the version contained in that file to set the correct version of npm for their use.
2. CI (Continuous Integration) workflows which need to know which version of npm to use can consume this file so that they are set up correctly.

**Comment by n8-dev** [comment]
> It would just take the version number from a defined file.

DDEV would just load the contents of the file, as its one line and only holds a node version string, this is compatible with what the nodejs_version property of DDEV already works with.

Basically do the same thing [n](https://github.com/tj/n)
It does not care if your file is a `.n-node-version` a `.node-version` or a `.nvmrc`

If you added other things, miss-formatted it (basically made it unreadable in some manner) DDEV should just throw an error as that is not suported.

The file just contains the version number, sometimes prepended with a `v`
Possible examples are
* `20.0.0`
* `20`
* `14.*`
* `v16`

Typical semver version assignment basically.

Other uses of the file aren't pertinent to DDEV, DDEV's responsibility is for local development currently.

Some of the details I have no control over with why these files are used:
* Some other people on a project unfortunately haven't switched to using DDEV yet. (Not something I can control) the use a `.n-node-version` file.
* One projects release process read a file for setting up its CircleCI test pipeline
* Another project reads a `.node-version` within a github action etc


The goal is to reduce the amount of locations that need to be maintained for the same thing.
Other areas have solved this by consolidating to a single point of reference.
DDEV should be able to read that file as well.

**Comment by rfay** [comment]
Is it true that `.nvmrc` should only contain a versionish thing in it?

I do see that the version can be specified lots of different ways. Maybe those would all work with DDEV's nodejs_version, since it uses `n` under the hood? https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc

**Comment by GuySartorelli** [comment]
I think it would be fine to say that files which has anything additional other than just the version number itself will be extra effort to manage - it would be simplest if DDEV throws an error in those cases especially since this is intended to be a generic implementation, and isn't specific to nvm or `.nvmrc`.

That said, if you would like the implementation to handle all possible contents that `nvm` allows, that could certainly be done.

**Comment by n8-dev** [comment]
Since DDEV uses `n` under the hood then can't it just match what `n` supports?
Which covers everything mentioned above.
https://github.com/tj/n?tab=readme-ov-file#specifying-nodejs-versions

**Comment by rfay** [comment]
I had assumed that `.nvmrc` would probably have more in it than a node.js version, which was a major reason for my pushback. It wouldn't surprise me if extra things would be added though...

**Comment by GuySartorelli** [comment]
It is possible for that file to contain comments. That file can also contain "a node version number (or any other string that nvm understands". But as stated above, DDEV uses `n` and `n` supports `.nvmrc` so that shouldn't be a problem.

Regardless of which, as I stated above, it would be totally acceptable if DDEV supported some subset of what `nvm` can support, if it came down to it (which it sounds like it won't because, again, `n` supports `.nvmrc`), because this is intended to be a general approach and not specific to `nvm` or any other specific tool.

**Comment by rfay** [comment]
How would a file be distinguished from a nodejs_version?

**Comment by GuySartorelli** [comment]
There are various approaches we could take:

1. Naively assume it's a file path - if there's no file, assume it's a node version
1. Naively assume it's a node version - if there are errors, check for a file
1. Check if it's a node version (semver) - if there are other accepted values such as  "latest", check if those too. If it's none of those, then look for a file.
1. Use a separate config name such as `nodejs_version_file`, which is for the file path. This comes with a ton of questions about what happens if both `nodejs_version` and `nodejs_version_file` are both used but the easiest resolution is to throw an error in that case.

I'd probably recommend option 1 for simplicity, or option 4 for a more intuitive experience.

**Comment by stasadev** [comment]
@n8-dev, @GuySartorelli, please test:

- #6420

**Comment by n8-dev** [comment]
I've never seen anything other than a version number in a nvmrc.

As for the other file, they all just contain valid version identifiers nothing more hence n being able to read them.


In fact I think @stasadev out thought us all!


I'll check that out soon though @stasadev  PR looks like the best way forward.

Simple.
Clear.
Elegant and no faffing with paths.

If someone wants paths to somewhere else for a specific file they could open a PR in the future.

(Assuming this works, will check tomorrow)

**Comment by stasadev** [comment]
> If someone wants paths to somewhere else for a specific file they could open a PR in the future.

I also took this into account (you can add a symbolic link to the parent directory, so `n` can see this file, an example is in the docs for my PR).

**Comment by n8-dev** [comment]
Thank you @stasadev 🎉
