### ISSUE TITLE
Mysql/MariaDB UTF8 for CakePHP app

### ISSUE THREAD

**Issue by dereuromark** [ddev/ddev#6428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The connection will not match the database content.
One has to manually adjust the config once they run into issues.

### Describe your solution

It would be nice if this snippet would be commented in automatically:

            /*
             * For MariaDB/MySQL the internal default changed from utf8 to utf8mb4, aka full utf-8 support, in CakePHP 3.6
             */
            //'encoding' => 'utf8mb4',
            
to

            /*
             * For MariaDB/MySQL the internal default changed from utf8 to utf8mb4, aka full utf-8 support, in CakePHP 3.6
             */
            'encoding' => 'utf8mb4',

https://github.com/cakephp/app/blob/ca45a282941596d4ddadd9ca94bf39fde2951798/config/app.php#L290

### Additional context

Refs https://github.com/ddev/ddev/pull/5888

**Comment by stasadev** [comment]
I don't think it's within DDEV's responsibility as there is no environment variable for `encoding`, and editing an existing file is a bad idea, the syntax can change at any time.

If this needs to be changed, it should be done on the CakePHP side.

/cc @ajibarra

**Comment by dereuromark** [comment]
Well, I would imagine this to be similar to enableDotEnvLoading()

Sth like:
```
func enableUtf8ForMysql(app *DdevApp, dbConnection) error {
        if (dbConnection != 'mysql') {
             return nil
        }

	bootstrapFileName := "config/bootstrap.php"
	bootstrapFilePath := filepath.Join(app.AppRoot, bootstrapFileName)
	envFunction := "//'encoding' => 'utf8mb4',"
	err := fileutil.ReplaceStringInFile(envFunction, strings.ReplaceAll(envFunction, "// ", ""), bootstrapFilePath, bootstrapFilePath)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by ajibarra** [comment]
I think it should work for MySQL because afair the default character set is utf8mb4.. however for MariaDB I think it is latin1 so it may cause issues. I will check and see how can this be addressed and what is the best approach.

**Comment by dereuromark** [comment]
FYI:
I think mariadb is the same.
I used `mariadb:10.11` for my tests, and without utf8mb4 it fails to properly work.

**Comment by dereuromark** [comment]
The main issue with CakePHP internal seems to be that at the time it is not known which DB service (type) is used, so the installer could only either do it fully or not at all.
This callback here would be able to do that more appropriately probably

**Comment by rfay** [comment]
I'm a little confused here, since DDEV creates the database with every setting set up for utf8mb4, see https://github.com/ddev/ddev/blob/master/containers/ddev-dbserver/files/etc/my.cnf

How is Craft getting something that is *not* utf8mb4? Because Craft is setting up a non-utf8mb4 client side?

Can you please say explicitly what the consequences of the problem are, how to demonstrate it, and what you do to fix it?

IMO Craft should always assume utf8mb4. It's been 15 years hasn't it, since this became essential because of emojis?

**Comment by dereuromark** [comment]
Yes
But the App opens the connection using non utf8mb4
Thus this fix to ensure the App Code fies the DB config

**Comment by rfay** [comment]
> Can you please say explicitly what the consequences of the problem are, how to demonstrate it, and what you do to fix it?

And in the process of describing that, think about why you opened this issue in the DDEV issue queue, you'll need to explain that.

**Comment by ajibarra** [comment]
@rfay I was discussing the issue with @dereuromark so basically cakephp defaults to utf8 and dev to utf8mb4.

So if you create/export (or load) a db into ddev instance with data included it may cause issues because of the different encoding.

What he is suggesting is just ensure that any ddev cakephp project uses utf8mb4 by default removing the // from 'encoding' in the app config file to ensure db encoding and cakephp encoding matches.

I will take a look next week and prepare a pull request and you guys can evaluate if you agree or not with the solution proposed.

I applied a similar approach to ensure the environment file was loaded in bootstrap.php file.

Let me know if it makes sense to you.

Thank you!

**Comment by rfay** [comment]
Thanks! In addition I would sure encourage doing a CakePHP PR to always use utf8mb4 everywhere. The consequences of not doing so are quite significant, with user-generated content containing many emojis (and certain languages) resulting in truncated content, etc.

**Comment by dereuromark** [comment]
Jep
I opened https://github.com/cakephp/app/pull/1011 to clarify if we can do this

**Comment by dereuromark** [comment]
Ok this has been resolved in the App itself :)
Thx!
