### ISSUE TITLE
Traefik router healthcheck.sh gives no useful output when everything fails

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6463]
### Expected Behavior

When a healthcheck fails, it should give us some information about why it's failing. Right now, we don't have any.

See https://discord.com/channels/664580571770388500/1269927348447346689

### Actual Behavior

In the discord issue, we see that traefik is giving no output at all (https://gist.github.com/comanche76/d45b561a42f41e3684fe98e4bd9aff51#file-docker_inspect_ddev-router-txt): 
> {"Status":"unhealthy","FailingStreak":0,"Log":[]}

The healthcheck is https://github.com/ddev/ddev/blob/master/containers/ddev-traefik-router/traefik_healthcheck.sh

It does seem that if none of the happy cases work, it doesn't output any useful information. So in this case, it wasn't healthy, it wasn't initializing, and the curl on the router ping failed. 

However, we used curl -s on that, so we're not seeing that output. 

So we can improve the healthcheck.sh to give information on why it isn't healthy. Which case failed...

It may be that there are other healthchecks that aren't as good as they could be.

**Comment by rfay** [comment]
See also:
* https://github.com/ddev/ddev/issues/6417

**Comment by rfay** [comment]
Also, we're capturing very verbose debug logs, which could cause docker memory issues. For example, in https://github.com/ddev/ddev/actions/runs/11937681719/job/33274224547#step:16:10261 we have an enormous amount of output. We probably don't need DBG logging anyway, and that test doesn't need to report it when there's no problem:

https://github.com/ddev/ddev/blob/a82397976cb06a440b23a81a474ceda13a428ae1/pkg/ddevapp/ddevapp_test.go#L3755

**Comment by stasadev** [comment]
I understood why the healthcheck logs are empty if traefik is completely broken:

```
$ ddev start
...
Failed to start d11: ddev-router failed to become ready; logOutput=, err=ddev-router container is unhealthy, log=
Troubleshoot this with these commands: 
[
        docker logs ddev-router
        docker inspect --format "{{ json .State.Health }}" ddev-router | docker run -i --rm ddev/ddev-utilities jq -r
] 
```

Log shows the error, which is good (I broke it using `address123` instead of `address`):

```
$ docker logs ddev-router
{"level":"error","error":"command traefik error: field not found, node: address123","time":"2024-11-29T14:37:18Z","message":"Command error"}
```

And healthcheck logs are empty:

```
$ docker inspect --format "{{ json .State.Health }}" ddev-router | docker run -i --rm ddev/ddev-utilities jq -r
{
  "Status": "unhealthy",
  "FailingStreak": 0,
  "Log": []
}
```

It's because when the initial `command` fails, the healthcheck is not even executed:

https://github.com/ddev/ddev/blob/772b398d92e4d01181b3bd6873fa3b8191356220/pkg/ddevapp/router_compose_template.yaml#L1-L9

This can be changed if we use this:

```diff
-- --configFile=/mnt/ddev-global-cache/traefik/.static_config.yaml 
+- --configFile=/mnt/ddev-global-cache/traefik/.static_config.yaml || true
```

Container status will be `starting` (until it becomes `unhealthy` or `exited` depending on the OS), not `exited`, it will fail only after some time.

But in this case we will have the opposite situation, `docker logs ddev-router` will be empty, and `docker inspect` will contain the error.

I don't think we want that, because it will only increase the wait time and not fail right away.
