### ISSUE TITLE
Don't output `127.0.0.1` URL on `ddev start` or `ddev restart` (if router is enabled)

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6500]
On `ddev start` and `ddev restart` we show this at the end:

> Project can be reached at https://d11.ddev.site https://127.0.0.1:32810

If there are multiple hostnames or multiple fqdns we show all of them.

But the https://127.0.0.1 or http://127.0.0.1 sometimes confuses people who come from a world where all local dev is done on localhost. 

I think it would be better to just output this **when the router is enabled**

> Project can be reached at https://d11.ddev.site

(with any other other non-127.0.0.1 URLs)

If the router is disabled, the 127.0.0.1 URL is the only one available, so then it needs to be output.

**Comment by davearch** [comment]
Seems like it would be pretty simple to update the code GetAllURLs like so:
```go
if IsRouterDisabled(app) {
	httpsURLs = append(httpsURLs, app.GetWebContainerDirectHTTPSURL())
	httpURLs = append(httpURLs, app.GetWebContainerDirectHTTPURL())
	
}
```
As those functions return the 127.0.0.1 URLs.

However, as it stands it is currently like this:
```go
if !IsRouterDisabled(app) {
	httpsURLs = append(httpsURLs, app.GetWebContainerDirectHTTPSURL())
}
httpURLs = append(httpURLs, app.GetWebContainerDirectHTTPURL())
```
So httpURLs will always get the 127.0.0.1 URL and httpsURLs only get the 127.0.0.1 URL if the router is enabled. I'm not sure what the reason is for this little line so wanted to ask before attempting to change it. Thoughts?

**Comment by rfay** [comment]
I don't think it's correct to change GetAllURLs(), since those 127.0.0.1 URLs are correct and useful if you understand what you're doing. 

I think just changing `ddev start` to say something like

```
Project can be reached at https://d11.ddev.site/ - see ddev describe for alternate URLs
```

Something like that?

So `ddev start` with router enabled (default case) would only emit the primary URL.
