### ISSUE TITLE
Support for PIE - PHP Installer for Extensions when more extensions are supported

### ISSUE THREAD

**Issue by nickchomey** [ddev/ddev#6746]
I wonder if it could be beneficial to DDEV to make use of the new PHP Installer for Extensions. https://thephp.foundation/blog/2024/11/19/pie-pre-release/

**Comment by rfay** [comment]
Nice, thanks for pointing it out. There's not much in the list yet, but it sure looks promising, https://packagist.org/extensions

But APCU and xdebug are two that we're missing for PHP 8.4 right now. 

Have you tried installing any of these with PIE?

This might be a whole new strategy instead of depending on deb.sury.org, at least if it fully catches on, and with support of PHP Foundation maybe it will!

**Comment by rfay** [comment]
Thanks for pointing this out, we'll be watching for when more are supported, and you're welcome to poke when you see that happen. Closing for now.
