### ISSUE TITLE
Add MacPorts installation option for macOS

### ISSUE THREAD

**Issue by jlorenzetti** [ddev/ddev#6806]
DDEV is now available in MacPorts. Could we add MacPorts as an installation option in the macOS installation guide?

The installation can be done with:

```bash
sudo port install ddev
```

This would give macOS users another official package manager option alongside Homebrew.

I'm happy to submit a PR to update the documentation if you agree this would be useful.

**Comment by rfay** [comment]
Moved this to ddev/ddev, where it belongs, instead of the blog.

@jlorenzetti 

* If there's a way to change the recipe to use the downloadable released ddev binary (which is signed and notarized, as is required by macOS), could you take a look? So use the reliably prepared binary instead of building.
* We probably won't document or support something we don't have control of.

**Comment by jlorenzetti** [comment]
Hi @rfay,

Thank you for your response and for considering the integration of MacPorts. As far as I know, the MacPorts community typically only considers integrating precompiled binaries from external sources in exceptional circumstances. This is to maintain the integrity and security of the packages they provide.

Given this, it might not be the most suitable option to include MacPorts as an official installation method in the DDEV documentation, considering the interests of all parties involved.

Thanks for the great work on DDEV! 🙌

**Comment by rfay** [comment]
Thanks for experimenting with this. I don't think we'll consider something that's not officially signed and notarized.
